require("codeium").setup()
--   function()
--   vim.keymap.set("i", "<C-;>", function()
--     return vim.fn["codeium#Accept"]()
--   end, { expr = true, silent = true, noremap = true })
--   -- ... other mappings ...
--   vim.api.nvim_create_user_command("CodeiumChat", function(opts)
--     vim.fn["codeium#Chat"]()
--   end, { nargs = "*", desc = "Codeium Chat" })
-- end)
